FROM node:14.18.1-slim
WORKDIR /app

# Важно для кеширования слоев
# RUN npm update and npm update node
COPY app/package*.json ./
COPY app/.env.example ./

RUN npm ci

COPY app/. .

EXPOSE 8080

CMD npm start